// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/soat-46/ms-mail-sender/internal/global/domain/entities"
	"github.com/soat-46/ms-mail-sender/internal/global/infrastructure/clients/contracts"
	"github.com/soat-46/ms-mail-sender/internal/global/infrastructure/clients/providers"
	entities2 "github.com/soat-46/ms-mail-sender/internal/global/infrastructure/clients/providers/entities"
	"github.com/soat-46/ms-mail-sender/internal/global/infrastructure/configuration"
	"github.com/soat-46/ms-mail-sender/internal/mail"
	"github.com/soat-46/ms-mail-sender/internal/mail/domain/commands"
	"github.com/soat-46/ms-mail-sender/internal/mail/infrastructure/listeners"
	"github.com/soat-46/ms-mail-sender/internal/mail/infrastructure/services"
	"gopkg.in/gomail.v2"
	"os"
	"strconv"
)

// Injectors from wire.go:

func injectApps() []entities.App {
	settings := injectSettings()
	dialer := injectGoMail(settings)
	sendMailService := services.NewSendMailService(settings, dialer)
	renderMailTemplate := services.NewRenderMailTemplate()
	sendMailCommand := commands.NewSendMailCommand(sendMailService, renderMailTemplate)
	queueSettings := injectQueueSettings()
	sqsClient := injectSQSClient(queueSettings)
	sendErrorMailQueueListener := listeners.ProvideErrorListener(sendMailCommand, sqsClient)
	sendSuccessMailQueueListener := listeners.ProvideSuccessListener(sendMailCommand, sqsClient)
	app := mail.NewApp(sendErrorMailQueueListener, sendSuccessMailQueueListener)
	v := newApps(app)
	return v
}

// wire.go:

func injectSettings() *entities.Settings {
	from := os.Getenv("MAIL_FROM")
	host := os.Getenv("MAIL_HOST")
	port, _ := strconv.Atoi(os.Getenv("MAIL_PORT"))
	username := os.Getenv("MAIL_USERNAME")
	password := os.Getenv("MAIL_PASSWORD")

	return entities.NewSettings(from, host, port, username, password)
}

func injectGoMail(settings *entities.Settings) *gomail.Dialer {
	return gomail.NewDialer(settings.Host, settings.Port, settings.Username, settings.Password)
}

func injectQueueSettings() *entities2.QueueSettings {
	region := os.Getenv("AWS_SQS_REGION")
	username := os.Getenv("AWS_SQS_KEY")
	password := os.Getenv("AWS_SQS_SECRET")
	return entities2.NewQueueSettings(username, password, region)
}

func injectSQSClient(settings *entities2.QueueSettings) contracts.SQSClient {
	client, err := configuration.NewSQSClient(settings)
	if err != nil {
		panic(err)
	}
	return providers.NewSQSClientProvider(client)
}

func newApps(mail2 *mail.App) []entities.App {
	return []entities.App{mail2}
}
