services:
  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Porta AMQP (uso por apps)
      - "15672:15672"   # Porta do painel de administração
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: supersecure
    networks:
      - soatnet

networks:
  soatnet:
    driver: bridge
