services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Porta AMQP (uso por apps)
      - "15672:15672"   # Porta do painel de administração
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: supersecure
    networks:
      - soat_net

networks:
  soat_net:
    driver: bridge
